CREATE TABLE `AUTHOR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `AUTHOR_NAME` varchar(255) NOT NULL,
  `BIOGRAPHY` varchar(255) NOT NULL,
  `MINI_BIOGRAPHY` varchar(255) DEFAULT NULL,
  `IMGSRC` varchar(500) NOT NULL,
  `LANGUAGE` varchar(2) NOT NULL,
  `JOINED_ON` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_ffiibfpic09earlrraqgngf1o` (`AUTHOR_NAME`),
  KEY `IDX_CONTENT_AUTHOR_NAME` (`AUTHOR_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
